apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false

  - name: Wazuh-Indexer
    type: elasticsearch
    access: proxy
    url: http://wazuh-indexer:9200
    database: "wazuh-alerts-*"
    jsonData:
      esVersion: "8.0.0"
      timeField: "timestamp"
      logMessageField: "rule.description"
      logLevelField: "rule.level"
    editable: false
